services:

  # kafka Broker
  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9094"    # 외부(Host) 9092 -> 컨테이너 9094
      - "9093:9093"    # 컨트롤러용
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      
      # 리스너 설정
      # - PLAINTEXT: 내부 컨테이너 통신
      # - CONTROLLER: 메타데이터 관리용 내부 통신
      # - EXTERNAL: 외부(Host) 통신
      KAFKA_LOG_RETENTION_HOURS: 1           # 1시간이 지난 데이터는 삭제
      KAFKA_LOG_RETENTION_BYTES: 536870912   # 512MB가 넘으면 오래된 데이터 삭제
      KAFKA_LOG_SEGMENT_BYTES: 104857600     # 파일 단위를 100MB로 쪼개서 빨리 삭제되도록 함
      KAFKA_LOG_CLEANUP_POLICY: delete       # 삭제 정책 명시
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - kafka-net

  # kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - kafka-net

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.16.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - kafka-net

  # OpenSearch Dashboards
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.16.0
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch
    networks:
      - kafka-net
  
  # Service W1
  w1-service:
    build: .
    image: my-log-service:latest
    environment:
      APP_ROLE: W1
      INPUT_TOPIC: topic-a
      OUTPUT_TOPIC_1: topic-b
      OUTPUT_TOPIC_2: topic-c
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      OPENSEARCH_URI: http://opensearch:9200
    depends_on:
      - kafka
      - opensearch
    networks:
      - kafka-net

  # Service W2
  w2-service:
    image: my-log-service:latest
    environment:
      APP_ROLE: W2
      INPUT_TOPIC: topic-b
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      OPENSEARCH_URI: http://opensearch:9200
    depends_on:
      - kafka
      - opensearch
    networks:
      - kafka-net

  # Service W3
  w3-service:
    image: my-log-service:latest
    environment:
      APP_ROLE: W3
      INPUT_TOPIC: topic-c
      KAFKA_BOOTSTRAP_SERVER: kafka:9092
      OPENSEARCH_URI: http://opensearch:9200
    depends_on:
      - kafka
      - opensearch
    networks:
      - kafka-net

  # Log Generator
  log-generator:
    image: apache/kafka:4.1.1
    container_name: log-generator
    depends_on:
      - kafka
    entrypoint:
      - bash
      - -c
      - |
        echo 'Waiting for Kafka to be ready...'
        sleep 10
        
        echo 'Creating topic if not exists...'
        /opt/kafka/bin/kafka-topics.sh --create --topic topic-a --bootstrap-server kafka:9092 --partitions 3 --replication-factor 1 --if-not-exists
        
        echo 'Start generating logs...'
        while true; do
          echo "Log-$$(date +%s)-$$RANDOM" | /opt/kafka/bin/kafka-console-producer.sh --bootstrap-server kafka:9092 --topic topic-a
          sleep 1
        done
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge