apiVersion: v1
kind: Namespace
metadata:
  name: kafka-demo

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kafka-demo
data:
  KAFKA_BOOTSTRAP_SERVER: "kafka-headless:9092"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-headless.kafka-demo.svc.cluster.local:9092"
  OPENSEARCH_URI: "http://opensearch:9200"

  INPUT_TOPIC: "topic-a"
  OUTPUT_TOPIC_1: "topic-b"
  OUTPUT_TOPIC_2: "topic-c"
