global:
  registry: "172.16.30.128:5000"
  environment: production

license:
  tier: basic # basic | pro | enterprise

kafka:
  image:
    repository: apache/kafka
    tag: 4.1.1
  storage: 1Gi

opensearch:
  image:
    repository: opensearchproject/opensearch
    tag: 2.11.1
  ui:
    port: 9200

kafkaUI:
  image:
    repository: provectuslabs/kafka-ui
    tag: "v0.7.2"

apps:
  - name: w1-service
    image:
      repository: my-log-service
      tag: latest
      pullPolicy: IfNotPresent
    role: W1
    kafka:
      inputTopic: topic-a
      outputTopic1: topic-b
      outputTopic2: topic-c
      consumerGroup: group-W1
      lagThreshold: "10"

  - name: w2-service
    image:
      repository: my-log-service
      tag: latest
      pullPolicy: IfNotPresent
    role: W2
    kafka:
      inputTopic: topic-b
      consumerGroup: group-W2
      lagThreshold: "10"

  - name: w3-service
    image:
      repository: my-log-service
      tag: latest
      pullPolicy: IfNotPresent
    role: W3
    kafka:
      inputTopic: topic-c
      consumerGroup: group-W3
      lagThreshold: "10"

logGenerator:
  image:
    repository: apache/kafka
    tag: 4.1.1
    pullPolicy: IfNotPresent
  enabled: true
