global:
  environment: local

kafka:
  storage: 100Mi

# 앱 리스트 명시적 정의 (리스트 유실 방지)
apps:
  - name: w1-service
    image: { repository: my-log-service, tag: latest, pullPolicy: Never }
    role: W1
    kafka: { topic: topic-a, consumerGroup: group-W1, lagThreshold: "1" }
  - name: w2-service
    image: { repository: my-log-service, tag: latest, pullPolicy: Never }
    role: W2
  - name: w3-service
    image: { repository: my-log-service, tag: latest, pullPolicy: Never }
    role: W3