apiVersion: v1
kind: Service
metadata:
  name: w1-service
  namespace: kafka-demo
spec:
  type: ClusterIP # 온프레미스 환경에 따라 NodePort 또는 LoadBalancer로 변경 가능
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: w1-service
