apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVER: "kafka-0.kafka-headless.{{ .Release.Namespace }}.svc.cluster.local:9092"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-0.kafka-headless.{{ .Release.Namespace }}.svc.cluster.local:9092"
  OPENSEARCH_URI: "http://opensearch.{{ .Release.Namespace }}.svc.cluster.local:9200"
