{{- range .Values.apps }}
{{- if .name }}
---
# Service {{ .name }} Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: app
          # Global Registry 설정이 있으면 앞에 붙임
          image: "{{ if $.Values.global.registry }}{{ $.Values.global.registry }}/{{ end }}{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ROLE
              value: "{{ .role }}"
            {{- if .kafka }}
            - name: INPUT_TOPIC
              value: "{{ .kafka.inputTopic | default "" }}"
            {{- if .kafka.outputTopic1 }}
            - name: OUTPUT_TOPIC_1
              value: "{{ .kafka.outputTopic1 }}"
            {{- end }}
            {{- if .kafka.outputTopic2 }}
            - name: OUTPUT_TOPIC_2
              value: "{{ .kafka.outputTopic2 }}"
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: app-config
          ports:
            - containerPort: 8080
---
# Service {{ .name }} Service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ .name }}
  ports:
    - port: 80
      targetPort: 8080
{{- end }}
{{- end }}
